/**
 * Sprite scale overrides for Pokemon whose GIF sprites have a lot of
 * transparent whitespace (mostly birds / winged mons whose wings push
 * the visible body into a small portion of the canvas).
 *
 * Values are multipliers applied on top of the normal height-based scale.
 */
const SPRITE_SCALE_BOOST: Record<string, number> = {
  // Large / iconic winged Pokemon — most noticeable when too small
  charizard:          1.65,
  'charizard-megax':  1.65,
  'charizard-megay':  1.65,
  articuno:           1.65,
  'articuno-galar':   1.55,
  zapdos:             1.65,
  'zapdos-galar':     1.45,
  moltres:            1.65,
  'moltres-galar':    1.55,
  lugia:              1.55,
  hooh:               1.55,
  dragonite:          1.55,
  'dragonite-mega':   1.55,
  rayquaza:           1.55,
  'rayquaza-mega':    1.55,
  salamence:          1.50,
  'salamence-mega':   1.50,
  aerodactyl:         1.50,
  'aerodactyl-mega':  1.50,
  pidgeot:            1.50,
  'pidgeot-mega':     1.50,
  fearow:             1.50,
  noivern:            1.50,
  yveltal:            1.55,
  togekiss:           1.50,
  honchkrow:          1.50,
  staraptor:          1.50,
  braviary:           1.50,
  'braviary-hisui':   1.50,
  corviknight:        1.50,
  talonflame:         1.45,
  unfezant:           1.45,
  mandibuzz:          1.50,
  archeops:           1.50,
  decidueye:          1.45,
  'decidueye-hisui':  1.45,
  altaria:            1.45,
  'altaria-mega':     1.45,
  skarmory:           1.50,
  'skarmory-mega':    1.50,
  tropius:            1.45,
  flygon:             1.45,
  toucannon:          1.35,
  hawlucha:           1.35,
  tornadus:           1.45,
  'tornadus-therian': 1.45,
  thundurus:          1.45,
  'thundurus-therian':1.45,
  landorus:           1.45,
  'landorus-therian': 1.45,
  butterfree:         1.45,
  crobat:             1.35,
  noctowl:            1.35,
  xatu:               1.35,
  swanna:             1.35,
  pelipper:           1.35,
  cramorant:          1.35,

  // Mid-stage / smaller birds — slight boost
  pidgeotto:          1.25,
  golbat:             1.25,
  swellow:            1.35,
  staravia:           1.25,
  fletchinder:        1.25,
  tranquill:          1.25,
  corvisquire:        1.25,
  dartrix:            1.25,
  trumbeak:           1.25,
  archen:             1.25,
  rufflet:            1.25,
  vullaby:            1.25,
  murkrow:            1.25,
  oricorio:           1.35,
  'oricorio-pau':     1.35,
  'oricorio-sensu':   1.35,
  flapple:            1.35,
};

/** Return the sprite scale boost multiplier for a given Pokemon name. */
export function getSpriteBoost(pokemonName: string): number {
  return SPRITE_SCALE_BOOST[pokemonName.toLowerCase()] ?? 1;
}
